DROP TABLE IF EXISTS Devices;
CREATE TABLE DEVICES (
DEVICE_ID INT AUTO_INCREMENT PRIMARY KEY,
BRAND VARCHAR(50),
DEVICE VARCHAR(50) NOT NULL,
TECH VARCHAR(50),
G2 VARCHAR(50),
G3 VARCHAR(50),
G4 VARCHAR(50),
TAKEN_BY VARCHAR(50),
TAKEN_AT TIMESTAMP
);

CREATE SEQUENCE "DEVICES_SEQ"
MINVALUE 1
MAXVALUE 999999999
INCREMENT BY 1
START WITH 202700
NOCACHE
NOCYCLE;